import Foundation

/// Export Engine: converts a RenderDocument into various formats.
///
/// Supported formats: JSON, Markdown, HTML.
/// Future: PDF, Video.
public struct ExportEngine {

    // MARK: - JSON Export

    /// Export RenderDocument as JSON.
    public static func exportJSON(_ document: RenderDocument, pretty: Bool = true) throws -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = pretty
            ? [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
            : [.sortedKeys, .withoutEscapingSlashes]
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(document)
        return String(data: data, encoding: .utf8)!
    }

    // MARK: - Markdown Export

    /// Export RenderDocument as Markdown.
    public static func exportMarkdown(_ document: RenderDocument) -> String {
        var md = ""
        md += "# \(document.title)\n\n"
        md += "*\(document.subtitle)*\n\n"
        md += "---\n\n"

        for page in document.pages {
            for block in page.blocks {
                md += renderBlockAsMarkdown(block)
            }
            if page.pageType == .chapter || page.pageType == .content {
                md += "\n"
            }
        }

        md += "\n---\n\n"
        md += "*Generated by ChatMemoir*\n"
        return md
    }

    private static func renderBlockAsMarkdown(_ block: RenderBlock) -> String {
        switch block {
        case .title(let b):
            let prefix = b.level == 1 ? "# " : "## "
            return "\(prefix)\(displayText(b.rewrittenText, fallback: b.rawText))\n\n"

        case .subtitle(let b):
            return "*\(displayText(b.rewrittenText, fallback: b.rawText))*\n\n"

        case .paragraph(let b):
            return "\(displayText(b.rewrittenText, fallback: b.rawText))\n\n"

        case .quote(let b):
            let attr = b.attribution.map { " — *\($0)*" } ?? ""
            return "> \(displayText(b.rewrittenText, fallback: b.rawText))\(attr)\n\n"

        case .statistic(let b):
            return "**\(b.value)**\(b.unit ?? "") — \(b.label)\n\n"

        case .milestone(let b):
            let dateStr = b.date.map { ISO8601DateFormatter().string(from: $0) } ?? ""
            return "### 🏆 \(b.title)\n\n*\(dateStr)*\n\n\(displayText(b.rewrittenText, fallback: b.rawText))\n\n"

        case .divider(let b):
            switch b.style {
            case .plain: return "---\n\n"
            case .decorated: return "* * *\n\n"
            case .chapter: return "\n---\n\n"
            }

        case .spacer:
            return "\n"

        case .imagePlaceholder(let b):
            let cap = b.caption.map { " *\($0)*" } ?? ""
            return "> [Image: \(b.suggestedContent ?? "placeholder")]\(cap)\n\n"

        case .storyCard(let b):
            return "*Card: \(b.card.title)* — \(b.card.subtitle)\n\n"

        case .chapterHeader(let b):
            let emoji = emotionEmoji(b.emotion)
            return "\n## \(emoji) \(b.title)\n\n"

        case .emotionTag(let b):
            return "`\(b.label)` "
        }
    }

    // MARK: - HTML Export

    /// Export RenderDocument as a self-contained HTML page.
    public static func exportHTML(_ document: RenderDocument) -> String {
        let theme = document.theme
        var html = """
        <!DOCTYPE html>
        <html lang="zh">
        <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>\(document.title)</title>
        <style>
        body {
            font-family: '\(theme.typography.bodyFont)', serif;
            font-size: \(theme.typography.bodySize)px;
            line-height: 1.8;
            max-width: 700px;
            margin: \(theme.spacing.pageMargin)px auto;
            padding: \(theme.spacing.pageMargin)px;
            color: #2c2c2c;
            background: #fdfaf6;
        }
        h1 { font-family: '\(theme.typography.titleFont)', serif; font-size: \(theme.typography.titleSize)px; margin-bottom: 8px; }
        h2 { font-family: '\(theme.typography.titleFont)', serif; font-size: \(theme.typography.titleSize * 0.7)px; margin-top: \(theme.spacing.blockSpacing)px; }
        .subtitle { font-style: italic; color: #666; margin-bottom: \(theme.spacing.paragraphSpacing)px; }
        .cover { text-align: center; padding: 80px 0; }
        .stat { display: inline-block; margin: 16px 24px; text-align: center; }
        .stat-value { font-size: \(theme.typography.titleSize * 1.2)px; font-weight: bold; }
        .stat-label { font-size: \(theme.typography.captionSize)px; color: #999; }
        blockquote { border-left: 3px solid #e0d5c1; padding-left: 16px; color: #555; margin: \(theme.spacing.paragraphSpacing)px 0; }
        .divider { text-align: center; color: #ccc; margin: \(theme.spacing.blockSpacing)px 0; }
        .emotion-tag { display: inline-block; background: #f0e8d8; padding: 4px 12px; border-radius: \(theme.cornerRadius)px; font-size: \(theme.typography.captionSize)px; }
        .closing { text-align: center; padding: 60px 0; color: #888; }
        .page-break { page-break-after: always; }
        </style>
        </head>
        <body>
        """

        for page in document.pages {
            if page.pageType == .cover {
                html += "<div class='cover'>\n"
            } else if page.pageType == .closing {
                html += "<div class='closing'>\n"
            } else if page.pageType == .divider {
                html += "<div class='divider'>\n"
            } else {
                html += "<div>\n"
            }

            for block in page.blocks {
                html += renderBlockAsHTML(block)
            }

            html += "</div>\n"
            if page.pageType != .divider {
                html += "<div class='page-break'></div>\n"
            }
        }

        html += """
        </body>
        </html>
        """
        return html
    }

    private static func renderBlockAsHTML(_ block: RenderBlock) -> String {
        switch block {
        case .title(let b):
            let tag = b.level == 1 ? "h1" : "h2"
            return "<\(tag)>\(escapeHTML(displayText(b.rewrittenText, fallback: b.rawText)))</\(tag)>\n"

        case .subtitle(let b):
            return "<p class='subtitle'>\(escapeHTML(displayText(b.rewrittenText, fallback: b.rawText)))</p>\n"

        case .paragraph(let b):
            return "<p>\(escapeHTML(displayText(b.rewrittenText, fallback: b.rawText)))</p>\n"

        case .quote(let b):
            let attr = b.attribution.map { " — \(escapeHTML($0))" } ?? ""
            return "<blockquote>\(escapeHTML(displayText(b.rewrittenText, fallback: b.rawText)))\(attr)</blockquote>\n"

        case .statistic(let b):
            return """
            <div class='stat'>
            <div class='stat-value'>\(escapeHTML(b.value))\(escapeHTML(b.unit ?? ""))</div>
            <div class='stat-label'>\(escapeHTML(b.label))</div>
            </div>\n
            """

        case .milestone(let b):
            return "<h3>🏆 \(escapeHTML(b.title))</h3>\n<p>\(escapeHTML(displayText(b.rewrittenText, fallback: b.rawText)))</p>\n"

        case .divider:
            return "<hr>\n"

        case .spacer:
            return "<br>\n"

        case .imagePlaceholder(let b):
            let cap = b.caption.map { escapeHTML($0) } ?? ""
            return "<div style='background:#eee;padding:40px;text-align:center;color:#999'>[Image: \(escapeHTML(b.suggestedContent ?? ""))]<br><small>\(cap)</small></div>\n"

        case .storyCard(let b):
            return "<div style='border:1px solid #e0d5c1;padding:16px;border-radius:8px;margin:8px 0'><strong>\(escapeHTML(b.card.title))</strong><br>\(escapeHTML(b.card.subtitle))</div>\n"

        case .chapterHeader(let b):
            return "<h2>\(emotionEmoji(b.emotion)) \(escapeHTML(b.title))</h2>\n"

        case .emotionTag(let b):
            return "<span class='emotion-tag'>\(escapeHTML(b.label))</span> "
        }
    }

    // MARK: - Helpers

    private static func displayText(_ rewritten: String?, fallback: String) -> String {
        return rewritten ?? fallback
    }

    private static func escapeHTML(_ text: String) -> String {
        return text
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
    }

    private static func emotionEmoji(_ emotion: String) -> String {
        switch emotion {
        case "nostalgic": return "🕰️"
        case "joyful": return "🎉"
        case "warm": return "☀️"
        case "excited": return "🔥"
        case "bittersweet": return "🌧️"
        case "calm": return "🌿"
        case "reflective": return "💭"
        case "proud": return "🏆"
        default: return ""
        }
    }
}
